root -b -q -l 'plotFinalPlotsLowB_Systems.C(0,kTRUE,kFALSE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.0)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(0,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.0)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(1,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.0)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(2,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.0)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(3,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.0)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(0,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.25)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(0,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.50)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(0,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,1.75)'
root -b -q -l 'plotFinalPlotsLowB_Systems.C(0,kTRUE,kTRUE,kFALSE,0,2.5e9,kFALSE,kTRUE,1,0,1,2.0)'
root -b -q -l 'plotFinalPlotsComparison.C(0)'
root -b -q -l 'plotFinalPlotsComparison.C(1)'
root 'plotFinalPlotsTemperatureComparison.C(0,0)'
root 'plotFinalPlotsTemperatureComparison.C(0,1)'
